# Generated by Django 2.1.2 on 2018-10-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_konf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique_for_date=True)),
                ('comment', models.CharField(max_length=200)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_konf_app.Room')),
            ],
        ),
    ]
